<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AwesomeAssertions" Version="9.3.0" />
    <PackageVersion Include="FakeItEasy" Version="8.3.0" />
    <PackageVersion Include="FastEndpoints" Version="7.1.1" />
    <PackageVersion Include="FastEndpoints.Generator" Version="7.1.1" />
    <PackageVersion Include="FastEndpoints.Security" Version="7.1.1" />
    <PackageVersion Include="FastEndpoints.Swagger" Version="7.1.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="Reqnroll.xunit.v3" Version="3.2.1" />
    <PackageVersion Include="TngTech.ArchUnitNET.xUnitV3" Version="0.13.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="xunit.v3" Version="3.2.1" />
  </ItemGroup>
</Project>