using Central.Domain.Documents.Ports;
using Central.Domain.Ports;
using Microsoft.Extensions.Logging;

namespace Central.Domain.Documents.Services;

/// <summary>
/// Domain service for executing pipelines on documents.
/// </summary>
public sealed class PipelineExecutionService
{
    private readonly IPipelineRepository _pipelineRepository;
    private readonly IPipelineExecutionRepository _pipelineExecutionRepository;
    private readonly ITaskRepository _taskRepository;
    private readonly IDocumentRepository _documentRepository;
    private readonly TaskExecutionService _taskExecutionService;
    private readonly ITaskExecuterFactory _taskExecuterFactory;
    private readonly ILogger<PipelineExecutionService> _logger;

    public PipelineExecutionService(
        IPipelineRepository pipelineRepository,
        IPipelineExecutionRepository pipelineExecutionRepository,
        ITaskRepository taskRepository,
        IDocumentRepository documentRepository,
        TaskExecutionService taskExecutionService,
        ITaskExecuterFactory taskExecuterFactory,
        ILogger<PipelineExecutionService> logger)
    {
        _pipelineRepository = pipelineRepository;
        _pipelineExecutionRepository = pipelineExecutionRepository;
        _taskRepository = taskRepository;
        _documentRepository = documentRepository;
        _taskExecutionService = taskExecutionService;
        _taskExecuterFactory = taskExecuterFactory;
        _logger = logger;
    }

    /// <summary>
    /// Executes a pipeline on a specific document.
    /// </summary>
    /// <param name="pipelineId">The ID of the pipeline to execute.</param>
    /// <param name="documentId">The ID of the document to process.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The created pipeline execution with all task executions.</returns>
    /// <exception cref="InvalidOperationException">If pipeline or document not found.</exception>
    public async Task<PipelineExecution> ExecutePipelineAsync(
        long pipelineId,
        long documentId,
        CancellationToken cancellationToken = default)
    {
        var pipeline = await _pipelineRepository.GetByIdAsync(pipelineId, cancellationToken);
        if (pipeline == null)
        {
            throw new InvalidOperationException($"Pipeline with ID {pipelineId} not found.");
        }

        if (!pipeline.Enabled)
        {
            throw new InvalidOperationException($"Pipeline '{pipeline.Name}' is disabled and cannot be executed.");
        }

        var document = await _documentRepository.GetByIdAsync(documentId, cancellationToken);
        if (document == null)
        {
            throw new InvalidOperationException($"Document with ID {documentId} not found.");
        }

        _logger.LogInformation(
            "Executing pipeline {PipelineName} (ID: {PipelineId}) on document {DocumentId}",
            pipeline.Name,
            pipelineId,
            documentId);

        // Create pipeline execution record
        var execution = new PipelineExecution
        {
            Id = 0, // Will be generated by repository
            PipelineId = pipelineId,
            DocumentId = documentId,
            Status = ExecutionStatus.Running,
            StartedAt = DateTimeOffset.UtcNow
        };

        execution = await _pipelineExecutionRepository.CreateAsync(execution, cancellationToken);

        var taskExecutions = new List<TaskExecution>();

        try
        {
            // Execute steps in order
            var steps = pipeline.Steps.OrderBy(s => s.Order).ToList();

            foreach (var step in steps)
            {
                _logger.LogInformation(
                    "Executing pipeline step {Order}: {StepName} (Type: {StepType})",
                    step.Order,
                    step.Name,
                    step.StepType);

                if (step.StepType == PipelineStepType.TaskStep)
                {
                    if (step.TaskId == null)
                    {
                        throw new InvalidOperationException($"TaskStep '{step.Name}' has no TaskId configured.");
                    }

                    var taskExecution = await _taskExecutionService.ExecuteTaskAsync(
                        step.TaskId.Value,
                        documentId,
                        execution.Id,
                        cancellationToken);

                    taskExecutions.Add(taskExecution);

                    // If task failed, stop pipeline execution
                    if (taskExecution.Status == ExecutionStatus.Failed)
                    {
                        throw new InvalidOperationException(
                            $"Task step '{step.Name}' failed: {taskExecution.ErrorMessage}");
                    }
                }
                else if (step.StepType == PipelineStepType.WaitStep)
                {
                    if (step.WaitDurationSeconds == null || step.WaitDurationSeconds <= 0)
                    {
                        throw new InvalidOperationException(
                            $"WaitStep '{step.Name}' has invalid WaitDurationSeconds: {step.WaitDurationSeconds}");
                    }

                    // Use wait executer from factory
                    var waitExecuter = _taskExecuterFactory.GetWaitExecuter();
                    
                    var context = new TaskExecutionContext
                    {
                        Task = null!, // Wait steps don't have a task
                        Document = document,
                        PipelineExecutionId = execution.Id,
                        WaitDurationSeconds = step.WaitDurationSeconds.Value
                    };

                    await waitExecuter.ExecuteAsync(context, cancellationToken);
                }
            }

            // Update execution with success
            execution = execution with
            {
                Status = ExecutionStatus.Completed,
                CompletedAt = DateTimeOffset.UtcNow,
                TaskExecutions = taskExecutions
            };

            _logger.LogInformation(
                "Pipeline {PipelineName} (ID: {PipelineId}) completed successfully for document {DocumentId}",
                pipeline.Name,
                pipelineId,
                documentId);
        }
        catch (Exception ex)
        {
            _logger.LogError(
                ex,
                "Pipeline {PipelineName} (ID: {PipelineId}) failed for document {DocumentId}",
                pipeline.Name,
                pipelineId,
                documentId);

            execution = execution with
            {
                Status = ExecutionStatus.Failed,
                CompletedAt = DateTimeOffset.UtcNow,
                ErrorMessage = ex.Message,
                TaskExecutions = taskExecutions
            };
        }

        return await _pipelineExecutionRepository.UpdateAsync(execution, cancellationToken);
    }

    /// <summary>
    /// Processes pending documents for all enabled pipelines.
    /// </summary>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The number of pipeline executions created.</returns>
    public async Task<int> ProcessPendingDocumentsAsync(CancellationToken cancellationToken = default)
    {
        var pipelines = await _pipelineRepository.GetAllAsync(cancellationToken);
        var enabledPipelines = pipelines
            .Where(p => p.Enabled && p.TriggerState.HasValue)
            .ToList();

        if (!enabledPipelines.Any())
        {
            _logger.LogDebug("No enabled pipelines with trigger states found for background processing.");
            return 0;
        }

        var executionCount = 0;

        foreach (var pipeline in enabledPipelines)
        {
            var documents = await _documentRepository.GetByStateAsync(pipeline.TriggerState!.Value, cancellationToken);

            foreach (var document in documents)
            {
                try
                {
                    // Update document state before processing
                    var updatedDocument = document with { State = DocumentState.Processing };
                    await _documentRepository.UpdateAsync(updatedDocument, cancellationToken);

                    await ExecutePipelineAsync(pipeline.Id, document.Id, cancellationToken);

                    // Update document state after successful processing
                    updatedDocument = updatedDocument with { State = DocumentState.Processed };
                    await _documentRepository.UpdateAsync(updatedDocument, cancellationToken);

                    executionCount++;
                }
                catch (Exception ex)
                {
                    _logger.LogError(
                        ex,
                        "Failed to process document {DocumentId} with pipeline {PipelineId}",
                        document.Id,
                        pipeline.Id);
                }
            }
        }

        return executionCount;
    }
}
