using Central.Domain.Documents.Ports;
using Microsoft.Extensions.Logging;

namespace Central.Domain.Documents.Services;

/// <summary>
/// Domain service for executing AI tasks on documents.
/// </summary>
public sealed class TaskExecutionService
{
    private readonly ITaskRepository _taskRepository;
    private readonly ITaskExecutionRepository _taskExecutionRepository;
    private readonly IDocumentRepository _documentRepository;
    private readonly ILogger<TaskExecutionService> _logger;

    public TaskExecutionService(
        ITaskRepository taskRepository,
        ITaskExecutionRepository taskExecutionRepository,
        IDocumentRepository documentRepository,
        ILogger<TaskExecutionService> logger)
    {
        _taskRepository = taskRepository;
        _taskExecutionRepository = taskExecutionRepository;
        _documentRepository = documentRepository;
        _logger = logger;
    }

    /// <summary>
    /// Executes a task on a specific document.
    /// </summary>
    /// <param name="taskId">The ID of the task to execute.</param>
    /// <param name="documentId">The ID of the document to process.</param>
    /// <param name="pipelineExecutionId">Optional pipeline execution ID if executed as part of a pipeline.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The created task execution.</returns>
    /// <exception cref="InvalidOperationException">If task or document not found.</exception>
    public async Task<TaskExecution> ExecuteTaskAsync(
        long taskId,
        long documentId,
        long? pipelineExecutionId = null,
        CancellationToken cancellationToken = default)
    {
        var task = await _taskRepository.GetByIdAsync(taskId, cancellationToken);
        if (task == null)
        {
            throw new InvalidOperationException($"Task with ID {taskId} not found.");
        }

        if (!task.Enabled)
        {
            throw new InvalidOperationException($"Task '{task.Name}' is disabled and cannot be executed.");
        }

        var document = await _documentRepository.GetByIdAsync(documentId, cancellationToken);
        if (document == null)
        {
            throw new InvalidOperationException($"Document with ID {documentId} not found.");
        }

        _logger.LogInformation(
            "Executing task {TaskName} (ID: {TaskId}) on document {DocumentId}",
            task.Name,
            taskId,
            documentId);

        // Create task execution record
        var execution = new TaskExecution
        {
            Id = 0, // Will be generated by repository
            TaskId = taskId,
            DocumentId = documentId,
            PipelineExecutionId = pipelineExecutionId,
            Status = ExecutionStatus.Running,
            StartedAt = DateTimeOffset.UtcNow
        };

        execution = await _taskExecutionRepository.CreateAsync(execution, cancellationToken);

        try
        {
            // Execute the task based on its type
            var result = task.TaskType switch
            {
                TaskType.AzureOpenAI => await ExecuteAzureOpenAITaskAsync(task, document, cancellationToken),
                TaskType.AzureDocumentIntelligence => await ExecuteAzureDocumentIntelligenceTaskAsync(task, document, cancellationToken),
                _ => throw new NotSupportedException($"Task type {task.TaskType} is not supported.")
            };

            // Update execution with result
            execution = execution with
            {
                Status = ExecutionStatus.Completed,
                CompletedAt = DateTimeOffset.UtcNow,
                Result = result
            };

            _logger.LogInformation(
                "Task {TaskName} (ID: {TaskId}) completed successfully for document {DocumentId}",
                task.Name,
                taskId,
                documentId);
        }
        catch (Exception ex)
        {
            _logger.LogError(
                ex,
                "Task {TaskName} (ID: {TaskId}) failed for document {DocumentId}",
                task.Name,
                taskId,
                documentId);

            execution = execution with
            {
                Status = ExecutionStatus.Failed,
                CompletedAt = DateTimeOffset.UtcNow,
                ErrorMessage = ex.Message
            };
        }

        return await _taskExecutionRepository.UpdateAsync(execution, cancellationToken);
    }

    private async Task<string> ExecuteAzureOpenAITaskAsync(
        ProcessingTask task,
        Document document,
        CancellationToken cancellationToken)
    {
        // TODO: Implement Azure OpenAI SDK integration
        // This is a placeholder for the actual implementation
        _logger.LogInformation(
            "Executing Azure OpenAI task with deployment: {Deployment}, prompt: {Prompt}",
            task.Configuration.AzureModelOrDeployment,
            task.Configuration.Prompt?.Length > 50 
                ? task.Configuration.Prompt[..50] + "..." 
                : task.Configuration.Prompt);

        await System.Threading.Tasks.Task.Delay(100, cancellationToken); // Simulate API call

        return "{\"status\": \"success\", \"message\": \"Azure OpenAI task executed (placeholder)\"}";
    }

    private async Task<string> ExecuteAzureDocumentIntelligenceTaskAsync(
        ProcessingTask task,
        Document document,
        CancellationToken cancellationToken)
    {
        // TODO: Implement Azure Document Intelligence SDK integration
        // This is a placeholder for the actual implementation
        _logger.LogInformation(
            "Executing Azure Document Intelligence task with model: {Model}",
            task.Configuration.AzureModelOrDeployment);

        await System.Threading.Tasks.Task.Delay(100, cancellationToken); // Simulate API call

        return "{\"status\": \"success\", \"message\": \"Azure Document Intelligence task executed (placeholder)\"}";
    }
}
