using Central.Domain.Documents.Ports;
using Central.Domain.Ports;
using Microsoft.Extensions.Logging;

namespace Central.Domain.Documents.Services;

/// <summary>
/// Domain service for executing AI tasks on documents.
/// </summary>
public sealed class TaskExecutionService
{
    private readonly ITaskRepository _taskRepository;
    private readonly ITaskExecutionRepository _taskExecutionRepository;
    private readonly IDocumentRepository _documentRepository;
    private readonly ITaskExecuterFactory _taskExecuterFactory;
    private readonly ILogger<TaskExecutionService> _logger;

    public TaskExecutionService(
        ITaskRepository taskRepository,
        ITaskExecutionRepository taskExecutionRepository,
        IDocumentRepository documentRepository,
        ITaskExecuterFactory taskExecuterFactory,
        ILogger<TaskExecutionService> logger)
    {
        _taskRepository = taskRepository;
        _taskExecutionRepository = taskExecutionRepository;
        _documentRepository = documentRepository;
        _taskExecuterFactory = taskExecuterFactory;
        _logger = logger;
    }

    /// <summary>
    /// Executes a task on a specific document.
    /// </summary>
    /// <param name="taskId">The ID of the task to execute.</param>
    /// <param name="documentId">The ID of the document to process.</param>
    /// <param name="pipelineExecutionId">Optional pipeline execution ID if executed as part of a pipeline.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The created task execution.</returns>
    /// <exception cref="InvalidOperationException">If task or document not found.</exception>
    public async Task<TaskExecution> ExecuteTaskAsync(
        long taskId,
        long documentId,
        long? pipelineExecutionId = null,
        CancellationToken cancellationToken = default)
    {
        var task = await _taskRepository.GetByIdAsync(taskId, cancellationToken);
        if (task == null)
        {
            throw new InvalidOperationException($"Task with ID {taskId} not found.");
        }

        if (!task.Enabled)
        {
            throw new InvalidOperationException($"Task '{task.Name}' is disabled and cannot be executed.");
        }

        var document = await _documentRepository.GetByIdAsync(documentId, cancellationToken);
        if (document == null)
        {
            throw new InvalidOperationException($"Document with ID {documentId} not found.");
        }

        _logger.LogInformation(
            "Executing task {TaskName} (ID: {TaskId}) on document {DocumentId}",
            task.Name,
            taskId,
            documentId);

        // Create task execution record
        var execution = new TaskExecution
        {
            Id = 0, // Will be generated by repository
            TaskId = taskId,
            DocumentId = documentId,
            PipelineExecutionId = pipelineExecutionId,
            Status = ExecutionStatus.Running,
            StartedAt = DateTimeOffset.UtcNow
        };

        execution = await _taskExecutionRepository.CreateAsync(execution, cancellationToken);

        try
        {
            // Get the appropriate executer for this task type
            var executer = _taskExecuterFactory.GetExecuter(task.TaskType);
            
            // Create execution context
            var context = new TaskExecutionContext
            {
                Task = task,
                Document = document,
                PipelineExecutionId = pipelineExecutionId
            };

            // Execute the task
            var result = await executer.ExecuteAsync(context, cancellationToken);

            // Update execution with result
            execution = execution with
            {
                Status = ExecutionStatus.Completed,
                CompletedAt = DateTimeOffset.UtcNow,
                Result = result
            };

            _logger.LogInformation(
                "Task {TaskName} (ID: {TaskId}) completed successfully for document {DocumentId}",
                task.Name,
                taskId,
                documentId);
        }
        catch (Exception ex)
        {
            _logger.LogError(
                ex,
                "Task {TaskName} (ID: {TaskId}) failed for document {DocumentId}",
                task.Name,
                taskId,
                documentId);

            execution = execution with
            {
                Status = ExecutionStatus.Failed,
                CompletedAt = DateTimeOffset.UtcNow,
                ErrorMessage = ex.Message
            };
        }

        return await _taskExecutionRepository.UpdateAsync(execution, cancellationToken);
    }
}
